In [5]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [6]:
data=pd.read_csv("Churn_Modelling.csv")

In [7]:
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [8]:
data=data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)
data.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1
3          699    France  Female  ...               0         93826.63       0
4          850     Spain  Female  ...               1         79084.10       0

[5 rows x 11 columns]

In [9]:
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])

In [10]:
from sklearn.preprocessing import OneHotEncoder
one_hot_encoder_geography=OneHotEncoder()
geography_encoded=one_hot_encoder_geography.fit_transform(data[['Geography']])
geography_encoded

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [11]:
one_hot_encoder_geography.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [12]:
geo_encoded_df=pd.DataFrame(geography_encoded.toarray(), columns=one_hot_encoder_geography.get_feature_names_out(['Geography']))

In [13]:
data=pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)

In [14]:
with open("label_encoder_gender.pkl","wb")as file:
    pickle.dump(label_encoder_gender,file)
with open("one_hot_encoder_geography.pkl","wb")as file:
    pickle.dump(one_hot_encoder_geography,file)

In [15]:
x=data.drop("Exited", axis=1)
y=data["Exited"]

In [16]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=42)

In [17]:
x_train

      CreditScore  Gender  ...  Geography_Germany  Geography_Spain
9254          686       1  ...                0.0              0.0
1561          632       1  ...                1.0              0.0
1670          559       1  ...                0.0              1.0
6087          561       0  ...                0.0              0.0
6669          517       1  ...                0.0              0.0
...           ...     ...  ...                ...              ...
5734          768       1  ...                0.0              0.0
5191          682       0  ...                0.0              0.0
5390          735       0  ...                0.0              0.0
860           667       1  ...                0.0              0.0
7270          697       1  ...                1.0              0.0

[8000 rows x 12 columns]

In [18]:
y_train

9254    0
1561    0
1670    1
6087    1
6669    1
       ..
5734    0
5191    0
5390    1
860     1
7270    0
Name: Exited, Length: 8000, dtype: int64

In [19]:
x_test

      CreditScore  Gender  ...  Geography_Germany  Geography_Spain
6252          596       1  ...                1.0              0.0
4684          623       1  ...                0.0              0.0
1731          601       0  ...                0.0              1.0
4742          506       1  ...                1.0              0.0
4521          560       0  ...                0.0              1.0
...           ...     ...  ...                ...              ...
6412          602       0  ...                1.0              0.0
8285          609       1  ...                0.0              0.0
7853          730       0  ...                0.0              0.0
1095          692       1  ...                0.0              0.0
6929          628       1  ...                1.0              0.0

[2000 rows x 12 columns]

In [20]:
y_test

6252    0
4684    0
1731    0
4742    0
4521    0
       ..
6412    1
8285    0
7853    1
1095    1
6929    1
Name: Exited, Length: 2000, dtype: int64

In [21]:
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [22]:
x_train_scaled

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [23]:
with open("scaler.pkl", "wb") as file:
    pickle.dump(scaler, file)

ANN IMPLEMENTATION

In [24]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [25]:
models= Sequential([
    Dense(64, activation='relu', input_shape=(x_train_scaled.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

WARNING:tensorflow:From c:\Users\Asus\Desktop\dl_project\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [26]:
models.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [28]:

import tensorflow


opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()

In [29]:
models.compile(optimizer=opt,loss=loss,metrics=['accuracy'])

In [30]:
lod_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback=TensorBoard(log_dir=lod_dir, histogram_freq=1)

In [33]:
early_stopping_callback=EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [35]:
#train the model
history=models.fit(x_train,y_train,validation_data=(x_test, y_test), callbacks=[tensorboard_callback, early_stopping_callback],verbose=1,epochs=100)

Epoch 1/100
250/250 [==============================] - 2s 6ms/step - loss: 33.0929 - accuracy: 0.6867 - val_loss: 20.6018 - val_accuracy: 0.6590
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 19.1160 - accuracy: 0.6775 - val_loss: 11.8216 - val_accuracy: 0.4955
Epoch 3/100
250/250 [==============================] - 1s 5ms/step - loss: 5.5974 - accuracy: 0.6773 - val_loss: 1.6791 - val_accuracy: 0.7330
Epoch 4/100
250/250 [==============================] - 2s 6ms/step - loss: 2.5771 - accuracy: 0.6866 - val_loss: 2.0690 - val_accuracy: 0.7725
Epoch 5/100
250/250 [==============================] - 1s 5ms/step - loss: 1.0560 - accuracy: 0.7116 - val_loss: 0.8832 - val_accuracy: 0.8030
Epoch 6/100
250/250 [==============================] - 1s 5ms/step - loss: 1.0148 - accuracy: 0.7243 - val_loss: 0.6466 - val_accuracy: 0.8040
Epoch 7/100
250/250 [==============================] - 1s 6ms/step - loss: 0.7085 - accuracy: 0.7311 - val_loss: 0.5351 - val_accuracy: 0.7865
Epoch 8/100
250/250 [==============================] - 1s 5ms/step - loss: 0.6349 - accuracy: 0.7541 - val_loss: 0.5467 - val_accuracy: 0.8035
Epoch 9/100
250/250 [==============================] - 1s 6ms/step - loss: 0.5553 - accuracy: 0.7770 - val_loss: 0.5257 - val_accuracy: 0.7965
Epoch 10/100
250/250 [==============================] - 2s 6ms/step - loss: 0.5514 - accuracy: 0.7791 - val_loss: 0.4981 - val_accuracy: 0.8040
Epoch 11/100
250/250 [==============================] - 2s 6ms/step - loss: 0.5197 - accuracy: 0.7934 - val_loss: 0.4923 - val_accuracy: 0.8035
Epoch 12/100
250/250 [==============================] - 1s 6ms/step - loss: 0.5072 - accuracy: 0.7944 - val_loss: 0.4900 - val_accuracy: 0.8035
Epoch 13/100
250/250 [==============================] - 1s 4ms/step - loss: 0.5043 - accuracy: 0.7945 - val_loss: 0.4915 - val_accuracy: 0.8035
Epoch 14/100
250/250 [==============================] - 1s 5ms/step - loss: 0.5085 - accuracy: 0.7939 - val_loss: 0.4951 - val_accuracy: 0.8035
Epoch 15/100
250/250 [==============================] - 1s 5ms/step - loss: 0.5129 - accuracy: 0.7924 - val_loss: 0.4967 - val_accuracy: 0.8035
Epoch 16/100
250/250 [==============================] - 1s 5ms/step - loss: 0.5085 - accuracy: 0.7945 - val_loss: 0.4959 - val_accuracy: 0.8035
Epoch 17/100
250/250 [==============================] - 2s 6ms/step - loss: 0.5085 - accuracy: 0.7943 - val_loss: 0.4960 - val_accuracy: 0.8035
Epoch 18/100
250/250 [==============================] - 1s 5ms/step - loss: 0.5082 - accuracy: 0.7943 - val_loss: 0.4980 - val_accuracy: 0.8035
Epoch 19/100
250/250 [==============================] - 1s 5ms/step - loss: 0.5085 - accuracy: 0.7945 - val_loss: 0.4986 - val_accuracy: 0.8035
Epoch 20/100
250/250 [==============================] - 1s 5ms/step - loss: 0.5079 - accuracy: 0.7945 - val_loss: 0.4964 - val_accuracy: 0.8035
Epoch 21/100
250/250 [==============================] - 1s 5ms/step - loss: 0.5082 - accuracy: 0.7945 - val_loss: 0.5369 - val_accuracy: 0.8035
Epoch 22/100
250/250 [==============================] - 1s 4ms/step - loss: 0.5170 - accuracy: 0.7945 - val_loss: 0.4958 - val_accuracy: 0.8035

In [45]:
models.save("models.h5")

c:\Users\Asus\Desktop\dl_project\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [ ]:
# load tensorboard extension
# No import needed

%load_ext tensorboard
%pip install "setuptools<81.0.0"

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard
Requirement already satisfied: setuptools<81.0.0 in .\venv\Lib\site-packages (80.10.2)
Note: you may need to restart the kernel to use updated packages.

Reusing TensorBoard on port 6006 (pid 16316), started 0:06:25 ago. (Use '!kill 16316' to kill it.)

In [44]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 16316), started 0:19:31 ago. (Use '!kill 16316' to kill it.)