In [1]:
import pandas as pd
import numpy as np

In [3]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import load_model
import pickle

In [8]:
models=load_model('models.h5')
with open('scaler.pkl', 'rb') as file:
    scaler = pickle.load(file)
with open('label_encoder_gender.pkl', 'rb') as file:
    label_encoder_gender=pickle.load(file)
with open('one_hot_encoder_geography.pkl', 'rb') as file:
    one_hot_encoder_geography=pickle.load(file)

WARNING:tensorflow:From c:\Users\Asus\Desktop\dl_project\venv\Lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

In [9]:
os.getcwd()
print(os.listdir())

['.git', 'Churn_Modelling.csv', 'experiment.ipynb', 'label_encoder_gender.pkl', 'logs', 'models.h5', 'one_hot_encoder_geography.pkl', 'prediction.ipynb', 'README.md', 'requirements.txt', 'scaler.pkl', 'venv']

In [10]:
input_data={
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 2,
    'Balance': 0.0,
    'NumOfProducts': 1,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [12]:
geography_encoded=one_hot_encoder_geography.transform([[input_data['Geography']]]).toarray()
geography_encoded_df=pd.DataFrame(geography_encoded, columns=one_hot_encoder_geography.get_feature_names_out(['Geography']))

c:\Users\Asus\Desktop\dl_project\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [13]:
geography_encoded_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [14]:
input_df=pd.DataFrame([input_data])

In [15]:
input_df['Gender']=label_encoder_gender.transform(input_df['Gender'])

In [16]:
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,2,0.0,1,1,1,50000

In [18]:
input_df=pd.concat([input_df.drop(['Geography'], axis=1), geography_encoded_df], axis=1)

In [19]:
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,2,0.0,1,1,1,50000,1.0,0.0,0.0

In [20]:
input_scaled=scaler.transform(input_df)

In [21]:
prediction=models.predict(input_scaled)
print("Predicted probability of churn:", prediction[0][0])

1/1 [==============================] - 0s 180ms/step
Predicted probability of churn: 0.055742554

In [23]:
prediction_probability=prediction[0][0]
print(prediction_probability)

0.055742554

In [25]:
if prediction_probability >0.5:
    print("The customer is likely to churn.")
else:
    print("The customer is unlikely to churn.")

The customer is unlikely to churn.